name: 'Hello JS Action'
description: 'A simple bundled JS action'
inputs:
  name:
    description: 'Name to greet'
    required: true
    default: 'World'
runs:
  using: 'node16'
  main: 'dist/index.js'
